### ISSUE TITLE
Force https in production?

### ISSUE THREAD

**Issue by thejmitchener** [ralphjsmit/laravel-glide#7]
Hey Ralph! I hope all is well.

I'm unsure if this is a setting I'm missing somewhere, however, I can't find any information about it.

How do I force laravel-glide to use HTTPS instead of HTTP in production?

Thanks in advance!

Take care,
Josh

**Comment by ralphjsmit** [comment]
Hi Josh, thanks for your message and question! 

In my case the HTTPS went all automatic in the projects I used the package. Perhaps setting an HTTPS url in the APP_URL would do it? And otherwise URL::forceScheme('https'); in a service provider?

Let me know!

**Comment by thejmitchener** [comment]
Hey Ralph,

Setting HTTPS in the env didn't fix the issue. Using the URL::forceScheme('https'); did work.

Thanks.

**Comment by thejmitchener** [comment]
Hey Ralph,

Setting HTTPS in the env didn't fix the issue. Using the URL::forceScheme('https'); did work.

Thanks.
